apiVersion: v1
description: A chart for a Cadvisor deployment
name: cadvisor
version: 2.3.3
appVersion: 0.49.1
home: https://github.com/google/cadvisor
sources:
  - https://github.com/google/cadvisor
  - https://github.com/ckotzbauer/helm-charts
keywords:
  - prometheus
  - cadvisor
  - monitoring
maintainers:
  - name: ckotzbauer
    email: christian.kotzbauer@gmail.com
