apiVersion: v1
description: nfs-client is an automatic provisioner that used your *already configured* NFS server, automatically creating Persistent Volumes.
name: nfs-client-provisioner
version: 1.1.0
appVersion: 3.1.0
home: https://github.com/kubernetes-incubator/external-storage/tree/master/nfs-client
sources:
  - https://github.com/kubernetes-incubator/external-storage/tree/master/nfs-client
  - https://github.com/ckotzbauer/helm-charts
maintainers:
  - name: ckotzbauer
    email: christian.kotzbauer@gmail.com
keywords:
  - nfs
  - storage
