apiVersion: v2
name: postgres-operator
description: Postgres Operator creates and manages PostgreSQL clusters running in Kubernetes
version: 1.11.0
appVersion: 1.11.0
home: https://github.com/zalando/postgres-operator
sources:
  - https://github.com/zalando/postgres-operator
  - https://github.com/ckotzbauer/helm-charts
keywords:
  - postgres
  - operator
  - cloud-native
  - patroni
  - spilo
maintainers:
  - name: ckotzbauer
    email: christian.kotzbauer@gmail.com
