apiVersion: v1
description: Alertmanager Webhook for Microsoft Teams
name: prometheus-msteams
version: 1.0.2
appVersion: 1.3.3
home: https://github.com/bzon/prometheus-msteams
sources:
  - https://github.com/bzon/prometheus-msteams
  - https://github.com/ckotzbauer/helm-charts
keywords:
  - prometheus
  - msteams
  - webhook
  - alertmanager
maintainers:
  - name: ckotzbauer
    email: christian.kotzbauer@gmail.com
