apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    {{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
    {{- end }}
    spec:
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      serviceAccountName: {{ template "app.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          {{- range $key, $value := .Values.args }}
            {{- if $value }}
            - --{{ $key }}={{ $value }}
            {{- else }}
            - --{{ $key }}
            {{- end }}
          {{- end }}
          {{- if .Values.ignoreRules }}
            - --grype-config-file=/vuln/grype.yaml
          {{- end }}
          {{- if .Values.filterConfig }}
            - --filter-config-file=/vuln/filter-config.yaml
          {{- end }}
          env:
          {{- if .Values.envVars }}
            {{ toYaml .Values.envVars | nindent 12 }}
          {{- end }}
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          livenessProbe:
            timeoutSeconds: 3
            httpGet:
              path: "/health"
              port: http
          readinessProbe:
            timeoutSeconds: 3
            httpGet:
              path: "/health"
              port: http
          securityContext:
{{ toYaml .Values.securityContext | indent 12 }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            {{- if .Values.useReportsEmptyDir }}
            - mountPath: /reports
              name: reports
            {{- end }}
            - mountPath: /work
              name: work
            - mountPath: /tmp
              name: tmp
            {{- if or .Values.ignoreRules .Values.filterConfig }}
            - mountPath: /vuln
              name: grype
            {{- end }}
            {{- if .Values.extraVolumeMounts }}
{{- toYaml .Values.extraVolumeMounts  | nindent 12 }}
            {{- end }}
      volumes:
        {{- if .Values.useReportsEmptyDir }}
        - name: reports
          emptyDir: {}
        {{- end }}
        - name: work
          emptyDir: {}
        - name: tmp
          emptyDir: {}
{{- if .Values.extraVolumes }}
{{- toYaml .Values.extraVolumes  | nindent 8 }}
{{- end }}
        {{- if or .Values.ignoreRules .Values.filterConfig }}
        - name: grype
          configMap:
            name: {{ template "app.name" . }}
        {{- end }}
    {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
