apiVersion: v2
description: Scans SBOMs for vulnerabilities
name: vulnerability-operator
version: 0.13.2
appVersion: 0.13.0
home: https://github.com/ckotzbauer/vulnerability-operator
sources:
  - https://github.com/ckotzbauer/vulnerability-operator
  - https://github.com/ckotzbauer/helm-charts
keywords:
  - kubernetes-operator
  - operator
  - sbom
  - grype
  - vulnerability
  - security
  - supply-chain-security
maintainers:
  - name: ckotzbauer
    email: git@ckotzbauer.de
