apiVersion: v1
description: Kubernetes-Operator to simplify RBAC configurations
name: access-manager
version: 0.5.3
appVersion: 0.5.1
home: https://github.com/ckotzbauer/access-manager
sources:
  - https://github.com/ckotzbauer/access-manager
  - https://github.com/ckotzbauer/helm-charts
keywords:
  - kubernetes-operator
  - operator
  - rbac
  - secret
maintainers:
  - name: ckotzbauer
    email: christian.kotzbauer@gmail.com
